TARGETS := libbinned.a
SUBDIRS :=

INSTALL_LIB := $(TARGETS)

LIBBINNED := $(OBJPATH)/libbinned.a

libbinned.a_DEPS = ccbconv_sub.o \
                 ccmconv_sub.o \
                 cballoc.o \
                 cbcadd.o \
                 cbcconv.o \
                 cbcdeposit.o \
                 cbcbadd.o \
                 cbcbaddv.o \
                 cbcbset.o \
                 cbcupdate.o \
                 cbnegate.o \
                 cbnum.o \
                 cbprint.o \
                 cbrenorm.o \
                 cbsetzero.o \
                 cbsbset.o \
                 cbsize.o \
                 cbsupdate.o \
                 cmcadd.o \
                 cmcconv.o \
                 cmcdeposit.o \
                 cmcmadd.o \
                 cmcmset.o \
                 cmcupdate.o \
                 cmdenorm.o \
                 cmnegate.o \
                 cmprint.o \
                 cmrenorm.o \
                 cmsetzero.o \
                 cmsmset.o \
                 cmsrescale.o \
                 cmsupdate.o \
                 ddbconv.o \
                 ddmconv.o \
                 dballoc.o \
                 dbbound.o \
                 dbdadd.o \
                 dbdconv.o \
                 dbddeposit.o \
                 dbdbadd.o \
                 dbdbaddsq.o \
                 dbdbaddv.o \
                 dbdbset.o \
                 dbdupdate.o \
                 dindex.o \
                 dbnegate.o \
                 dbnum.o \
                 dbprint.o \
                 dbrenorm.o \
                 dbsetzero.o \
                 dbsize.o \
                 dmbins.o \
                 dmdadd.o \
                 dmdconv.o \
                 dmddeposit.o \
                 dmdenorm.o \
                 dmdmadd.o \
                 dmdmaddsq.o \
                 dmdmset.o \
                 dmdrescale.o \
                 dmdupdate.o \
                 dmindex.o \
                 dmindex0.o \
                 dmnegate.o \
                 dmprint.o \
                 dmrenorm.o \
                 dmsetzero.o \
                 dscale.o \
                 sballoc.o \
                 sbbound.o \
                 sindex.o \
                 sbnegate.o \
                 sbnum.o \
                 sbprint.o \
                 sbrenorm.o \
                 sbsadd.o \
                 sbsconv.o \
                 sbsdeposit.o \
                 sbsetzero.o \
                 sbsbadd.o \
                 sbsbaddsq.o \
                 sbsbaddv.o \
                 sbsbset.o \
                 sbsbze.o \
                 sbsupdate.o \
                 smbins.o \
                 smdenorm.o \
                 smindex.o \
                 smindex0.o \
                 smnegate.o \
                 smprint.o \
                 smrenorm.o \
                 smsadd.o \
                 smsconv.o \
                 smsdeposit.o \
                 smsetzero.o \
                 smsmadd.o \
                 smsmaddsq.o \
                 smsmset.o \
                 smsrescale.o \
                 smsupdate.o \
                 sscale.o \
                 ssbconv.o \
                 ssmconv.o \
                 ufp.o \
                 ufpf.o \
                 zballoc.o \
                 zbdbset.o \
                 zbdupdate.o \
                 zbnegate.o \
                 zbnum.o \
                 zbprint.o \
                 zbrenorm.o \
                 zbsetzero.o \
                 zbsize.o \
                 zbzadd.o \
                 zbzconv.o \
                 zbzdeposit.o \
                 zbzbadd.o \
                 zbzbaddv.o \
                 zbzbset.o \
                 zbzupdate.o \
                 zmdenorm.o \
                 zmdmset.o \
                 zmdrescale.o \
                 zmdupdate.o \
                 zmnegate.o \
                 zmprint.o \
                 zmrenorm.o \
                 zmsetzero.o \
                 zmzadd.o \
                 zmzconv.o \
                 zmzdeposit.o \
                 zmzmadd.o \
                 zmzmset.o \
                 zmzupdate.o \
                 zzbconv_sub.o \
                 zzmconv_sub.o \
