//#define CBLAS
//#define SCALAPACK
#define __MKL_BLACS__

//#define RDGEMM_IGNORE_GEMMI
//#define RDGEMM_IGNORE_UPDATE
//#define RDGEMM_IGNORE_GMAMM
//#define RDGEMM_IGNORE_UNPACK
//#define RDGEMM_IGNORE_PACK
#define DSUMI2_UNROLL_STEP 4
//#define DGEMVI_IGNORE_UNROLL_2


// MAXIMUM NUMBER OF K
#define MAX_FOLD 4

#define MACHEPS DBL_EPSILON

